title: "Mushroom Guide"
description: "A Jekyll-powered site about mushrooms and recipes"
baseurl: ""  # Set this if deploying to GitHub Pages
url: "https://yourgithubusername.github.io"

collections:
  mushrooms:
    output: true
    permalink: /mushrooms/:name/

markdown: kramdown
theme: minima
