title: "Mushroom Guide"
description: "A Jekyll-powered site about mushrooms and recipes"
baseurl: "/mushroom-guide"  
url: "https://jullucy.github.io"

collections:
  mushrooms:
    output: true
    permalink: /mushrooms/:name/

markdown: kramdown
theme: minima
